### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [vldF/fedClient#1]
1. Я не до конца согласна с тем,  что предложенная реализация клиента — MVC в чистом виде (посмотрите, пожалуйста, пример, который  я Вам прислала на почту). Детали работы с конфигом при инициализации API стоит вынести в Api, так же, как и цикл поллинга сообщений. Для того, чтобы перерисовывать графику при этом, можно реализовать паттерн Publish-Subscribe и подписываться в main на обновления;
2. Относительно работы с конфигом — см. комментарий про архитектуру на исключениях к проекту сервера. Аналогично про ошибки — текстовые константы, про логирование, про возможность корректно завершить работу клиента не только в качестве исключения;
3. "/n" - не единственный вариант завершения строки. Для того, чтобы код был устойчив к возможным переездам между разными версиями ОС, имеет смысл пользоваться, например, [методом System.lineSeparator()](https://www.dotnetperls.com/newline-java). Аналогичное верно для разделителя путей ФС;
4. `if (lastAddedChatTextLen > 10)`  — магические константы — все еще — не очень хорошая идея;
5. Циклы перерисовки чата по полученным сообщениям/ по внутренним изменениям с логической точки зрения должны были бы быть разнесены (или условия должны быть модифицированы; пока читается с трудом) — но это, видимо, после publish/ subscribe уйдет;
6. Вспомогательный метод для тестов лучше держать в тестах;

**Comment by vldF** [comment]
2. Относительно проблем с архитектурой на исключениях. Если избавляться от исключений в целом по проекту, то код станет сложнее читать (нужны какие-то флаги, которые будут возвращаться при завершении метода и их надо как-то будет проверять). Если же Вы именно про работу с конфигом (вы же так называете файл пользователя, да?), проверку на его существование, то [архитектура на исключениях безопаснее](https://docs.oracle.com/javase/tutorial/essential/io/check.html). Да, она чуть медленнее, но я считаю, что в этом проекте это не критично

3. Хорошо, я переделаю, но всё равно считаю, что это не вызывает никаких проблем, так как
a. Lanterna нормально работает и в случае переноса обычным \n
b. Редактирование файла пользователя пользователем -- ненормальный механизм работы с программой
c. Сама jvm нормально работает как с файловым разделителем /, так и с \

5. Я решил, что патерн pub/sub в данном случае будет несколько избыточным (её эталонная реализация с каналом связи между отправителями и получателями событий). И заменил его на более простой патерн -- Observer

**Comment by vldF** [comment]
Добавил команду для выхода -- нужно написать /exit в поле для отправки сообщений и нажать enter

**Comment by vldF** [comment]
6. Да, согласен, так лучше, но этот метод использует закрытые поля класса. Да, можно решить задачу рефлексией, но решение, которое сделал я, мне нравится больше

**Comment by vldF** [comment]
1. Вынес работу с конфигом в API, но не согласен с полным выносом проверки обновления сообщений в него. Если я правильно понял Вас, вы предлагали вынести туда Thread, который отвечает за это. Да, это возможно, но это исказит дизайн кода, который есть сейчас. В классе, который является просто вспомогательным (Api) появятся потоки, которые, возможно, нужно как-то еще контролировать. А сейчас же все потоки, которые выполняются в фоне (поток проверки сообщений и обработки ввода пользователя в терминал) находятся рядом и их удобнее воспринимать, ИМХО

**Comment by Suntrie** [comment]
1. Про поток согласна, но по другой причине - в модели MVC он будет скорее методом контроллера;
2. По подпунктам все ок, про архитектуру на исключениях - все еще не совсем согласна. Шансов, что Вы получите ошибку доступа, ИМХО, меньше, чем того, что в папке запуска не будет поддиректории Users, а читаемость кода такое (хотя и более мотивированное) решение все еще ухудшает. В частности, возможно с этим связано появление следующего нюанса:
- если конструктор API в main выскочит с чем-либо, кроме ConnectionException, мы действительно должны продолжать выполнение кода?
3. a - исторически существует и вариант CR, например; b - валидно, считайте, что это отсылка к учебным пункта, и спасибо за реализацию; c- [пока не совсем поняла, что Вы имели в виду (есть варианты)](http://www.mit.edu/~6.005/fa09/resources/avoid-dependent-code.html);
4(4). V
4(5orig). Ок, неудачно сформулировала, так, безусловно, разумнее;
6. Ок 
___________
7. Константы в Java-подобных языках, как правило, именуются плюс-минус [в соответствии с](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) _-jfyi;_
8. С учетом того, насколько сильно перекрываются классы API в тестах проекта сервера и в клиенте, все-таки хотелось бы увидеть какую-то интеграцию, по возможности - либо через вынос во внешнюю либу, либо через переиспользование клиентского проекта в тестах серверного в виде либы. **Upd.** См. второй комментарий к тестам.

**Comment by vldF** [comment]
1, 2, 3, 4, 7 FIXED

**Comment by Suntrie** [comment]
1,2,3,4,7 - ок
8 - 👍
