### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Suntrie** [vldF/fedClient#2]
1. generateToken, раз уж он у Вас так часто встречается, вообще говоря, можно попробовать вынести в   отдельную библиотеку и подключать ее через тот же Gradle;

2. См. комментарии относительно тестирования к серверу.

**Comment by vldF** [comment]
1. Извините, но я не думаю, что есть смысл ради использования в двух проектах одного маленького блока кода создавать отдельную библиотеку. Но я изменил название этой функции в коде клиента (чтобы разорвать эту мнимую связь с тем же кодом, что и в сервере)

**Comment by Suntrie** [comment]
1. См. последний комментарий к проекту клиента - возможно, все же получится. Ради него, конечно, не стоит, стоит ради практики, но это не критично. Если говорить про переиспользование API - выглядит в обоих вариантах оправдано;
2. Суммарно - поскольку у Вас сейчас, по факту, тестируется API сервера + библиотечные прослойки для парсинга аргументов и работы с сетью (как задействованные в процессе), большую часть тестов стоит оставить только в сервере же. Все, что имеет смысл рассматривать здесь - работу с файлом пользователя в разных вариантах развития событий, работу с отображением (но сейчас это не актуально), отслеживать то, что отправленные нам сообщения к нам приходят.

**Comment by Suntrie** [comment]
Единственное, что в текущей версии кода - Api вроде как наследник Request-а (и с точки зрения умньшения объема кода расшариваемым стоило бы сделать Request)
